# SOURCE: https://pre-commit.com/hooks.html
# SOURCE: github.com/Yelp/Tron

exclude: '^(contrib|docs/conf.py|docs/gfx)'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    # -   id: check-added-large-files
    - id: check-ast
    # add/remove utf-8 from top of python files
    -   id: fix-encoding-pragma
        args: [--remove]
    - id: debug-statements
    - id: mixed-line-ending
      args: ['--fix=no']
    -   id: end-of-file-fixer
        exclude: CHANGELOG.md
    # -   id: check-json
    -   id: check-yaml
    # -   id: flake8
    #    exclude: testifycompat/
    # -   repo: https://gitlab.com/pycqa/flake8
    #     rev: 3.7.7
    #     hooks:
    #     -   id: flake8
    #         exclude: ^docs/source/conf.py$
    # -   id: pretty-format-json
    #     args: [
    #     '--autofix',
    #     '--indent', '4',
    #     '--no-sort-keys',
    #     ]
# -   repo: https://github.com/asottile/reorder_python_imports.git
#     rev: v1.3.2
#     hooks:
#     -   id: reorder-python-imports
#         args: [--py3-plus]
#         language_version: python3.6
-   repo: local
    hooks:
    -   id: patch-enforce-autospec
        name: mock.patch enforce autospec
        description: This hook ensures all mock.patch invocations specify an autospec
        entry: contrib/mock_patch_checker.py
        language: script
        files: ^tests/.*\.py$
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
# A tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language.
# -   repo: https://github.com/asottile/pyupgrade
#     rev: v1.21.0
#     hooks:
#     -   id: pyupgrade
#         args: [--py37-plus]

# - repo: https://github.com/pre-commit/mirrors-isort
#   rev: v4.3.4
#   hooks:
#   - id: isort
#     args: ["--recursive","--check-only","--diff","--verbose","./fake-medium-fastapi","./tests"]

# Statically populate the `known_third_party` `isort` setting.
# -   repo: https://github.com/asottile/seed-isort-config
#     rev: v1.9.1
#     hooks:
#     -   id: seed-isort-config
# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: v4.3.20
#     hooks:
#     -   id: isort
#         args: ["--recursive","--check-only","--diff","--verbose","./fake-medium-fastapi","./tests"]
